name: Stack

on:
    pull_request:
    push:
      branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            stack-yaml: stack-lts-17.yaml
            extra-args: ""
          - os: ubuntu-latest
            stack-yaml: stack-lts-18.yaml
            extra-args: ""
          - os: ubuntu-latest
            stack-yaml: stack-lts-19.yaml
            extra-args: ""
          - os: ubuntu-latest
            stack-yaml: stack-lts-20.yaml
            extra-args: ""
          - os: ubuntu-latest
            stack-yaml: stack-nightly.yaml
            extra-args: ""
          - os: macos-latest
            stack-yaml: stack-lts-17.yaml
            extra-args: ""
          - os: macos-latest
            stack-yaml: stack-lts-18.yaml
            extra-args: ""
          - os: macos-latest
            stack-yaml: stack-lts-19.yaml
            extra-args: ""
          - os: macos-latest
            stack-yaml: stack-lts-20.yaml
            extra-args: ""
          - os: macos-latest
            stack-yaml: stack-nightly.yaml
            extra-args: ""
          - os: windows-latest
            stack-yaml: stack-lts-17.yaml
            extra-args: ""
          - os: windows-latest
            stack-yaml: stack-lts-18.yaml
            extra-args: ""
          - os: windows-latest
            stack-yaml: stack-lts-19.yaml
            extra-args: ""
          - os: windows-latest
            stack-yaml: stack-lts-20.yaml
            extra-args: ""
          - os: windows-latest
            stack-yaml: stack-nightly.yaml
            extra-args: ""
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ${{ github.workspace }}/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-haskell-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-haskell-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack upgrade
            stack --version
            stack test --fast --stack-yaml=${{ matrix.stack-yaml }} ${{ matrix.extra-args }}
